# srcs/docker-compose.yml
version: '3.8'

services:

  nginx:
    build: ./requirements/nginx
    image: nginx          # nom = nom du service
    container_name: nginx
    restart: always       # redémarre en cas de crash
    ports:
      - "443:443"         # seul point d'entrée !
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    secrets:
      - db_password
      - credentials
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

# Volumes nommés — données stockées dans /home/login/data
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maito/data/wordpress

  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/maito/data/mariadb

# Réseau bridge personnalisé (obligatoire, host interdit)
networks:
  inception:
    driver: bridge

# Secrets — lus depuis des fichiers locaux
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt